version: "3"
services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: resourcespace
      MYSQL_DATABASE: resourcespace
      MYSQL_USER: resourcespace
      MYSQL_PASSWORD: resourcespace
    networks:
      - rsnet

  resourcespace:
    depends_on:
       - db
    volumes:
      - filestore:/var/www/resourcespace/filestore
      - include:/var/www/resourcespace/include
    # replace username/repo:tag with your name and image details
    # image: rs
    build: .
    ports:
      - "4000:80"
    restart: always
    environment:
      BASEURL: "http://localhost:4000"
    networks:
      - rsnet
networks:
  rsnet:
volumes:
    db_data:
    filestore:
    include: